/* eslint-env es2020 */
'use strict';

const crypto = require('crypto');
const os = require('os');
const { nanoId, ALPHA_BASE62 } = require('./generators');

// ── 1. Fractal / Recursive IDs ────────────────────────────────────────────────

/**
 * Creates a root ID for a fractal tree.
 * @param {string} [seed] Optional seed to make the root deterministic.
 */
function fractalRoot(seed) {
  const rootStr = seed ? crypto.createHash('sha256').update(String(seed)).digest('hex') : crypto.randomBytes(16).toString('hex');
  return `frc_${rootStr.slice(0, 16)}`;
}

/**
 * Deterministically derives a child ID from a parent ID.
 * @param {string} parentId The parent ID string.
 * @param {string|number} index The path or index (e.g. '1', 'child_a').
 */
function deriveFractalChild(parentId, index) {
  const hmac = crypto.createHmac('sha256', parentId).update(String(index)).digest('hex');
  // Re-encode to look like an ID
  return `frc_${hmac.slice(0, 16)}`;
}

// ── 2. Hardware-Bound IDs ─────────────────────────────────────────────────────

let _hardwareFingerprint = null;

function getHardwareFingerprint() {
  if (_hardwareFingerprint) return _hardwareFingerprint;
  
  const cpus = os.cpus() || [];
  const cpuModel = cpus.length > 0 ? cpus[0].model : 'unknown';
  const mem = os.totalmem();
  const interfaces = os.networkInterfaces();
  
  let mac = '00:00:00:00:00:00';
  // Try to find a non-internal MAC address
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (!iface.internal && iface.mac !== '00:00:00:00:00:00') {
        mac = iface.mac;
        break;
      }
    }
    if (mac !== '00:00:00:00:00:00') break;
  }
  
  const rawString = `${cpuModel}|${mem}|${mac}|${os.arch()}|${os.platform()}`;
  _hardwareFingerprint = crypto.createHash('sha256').update(rawString).digest('hex').slice(0, 8);
  return _hardwareFingerprint;
}

/**
 * Generates an ID cryptographically bound to the machine it is generated on.
 */
function hardwareId(opts = {}) {
  const fp = getHardwareFingerprint();
  const random = nanoId({ size: 12, alphabet: ALPHA_BASE62 });
  return `hw_${fp}_${random}`;
}

/**
 * Verifies if the given hardware ID was generated on the *current* machine.
 */
function verifyLocalHardware(id) {
  if (!id || !id.startsWith('hw_')) return false;
  const parts = id.split('_');
  if (parts.length < 3) return false;
  
  const currentFp = getHardwareFingerprint();
  return parts[1] === currentFp;
}

// ── 3. ZKP (Zero-Knowledge) Linked IDs ────────────────────────────────────────
// Uses ECDSA to prove two distinct random IDs were generated by the same identity
// without revealing the identity publicly (unless verifying).

function createZkpIdentity() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ec', {
    namedCurve: 'prime256v1'
  });
  
  return {
    publicKey: publicKey.export({ type: 'spki', format: 'pem' }),
    privateKey: privateKey.export({ type: 'pkcs8', format: 'pem' })
  };
}

function generateZkpId(identity) {
  // The ID is random to the outside world
  return `zk_${nanoId({ size: 16 })}`;
}

function createLinkProof(identity, idA, idB) {
  // Sign the concatenation of the two IDs
  const message = `${idA}::${idB}`;
  const sign = crypto.createSign('SHA256');
  sign.update(message);
  sign.end();
  const signature = sign.sign(identity.privateKey, 'base64');
  return signature;
}

function verifyLinkProof(idA, idB, proofToken, publicKey) {
  const message = `${idA}::${idB}`;
  const verify = crypto.createVerify('SHA256');
  verify.update(message);
  verify.end();
  try {
    return verify.verify(publicKey, proofToken, 'base64');
  } catch (e) {
    return false; // Malformed key or signature
  }
}

// ── 4. AI-Adaptive Compressed IDs ─────────────────────────────────────────────

class AdaptiveGenerator {
  constructor(opts = {}) {
    this.threshold = opts.threshold || 5; // Generate same prefix N times to trigger compression
    this.prefixCounts = new Map();
    this.dictionary = new Map(); // token -> prefix
    this.reverseDictionary = new Map(); // prefix -> token
    this.tokenCounter = 0;
  }

  _getNextToken() {
    const token = `~${ALPHA_BASE62[this.tokenCounter % 62]}`;
    this.tokenCounter++;
    return token;
  }

  /**
   * Generates a compressed ID given an input string or prefix+body.
   * Learns the prefix frequency and compresses it if it crosses the threshold.
   */
  generate(contextString) {
    // Basic heuristic: assume the first part of the string before a hyphen or underscore is a prefix,
    // or just learn fixed length chunks if no separator.
    let prefix = '';
    let remainder = contextString;
    
    const sepIdx = contextString.indexOf('-');
    if (sepIdx > 0) {
      prefix = contextString.substring(0, sepIdx + 1);
      remainder = contextString.substring(sepIdx + 1);
    } else if (contextString.length > 8) {
      prefix = contextString.substring(0, 6);
      remainder = contextString.substring(6);
    } else {
      // Too short to adapt
      return contextString;
    }

    // Check if already in dictionary
    if (this.reverseDictionary.has(prefix)) {
      const token = this.reverseDictionary.get(prefix);
      return `${token}${remainder}`;
    }

    // Update frequency
    const currentCount = (this.prefixCounts.get(prefix) || 0) + 1;
    this.prefixCounts.set(prefix, currentCount);

    if (currentCount >= this.threshold) {
      // Add to dictionary
      const token = this._getNextToken();
      this.dictionary.set(token, prefix);
      this.reverseDictionary.set(prefix, token);
      return `${token}${remainder}`;
    }

    return contextString;
  }

  /**
   * Decompresses an ID back to its original state based on the learned dictionary.
   */
  decompress(id) {
    if (id.startsWith('~') && id.length >= 2) {
      const token = id.substring(0, 2);
      if (this.dictionary.has(token)) {
        const prefix = this.dictionary.get(token);
        return `${prefix}${id.substring(2)}`;
      }
    }
    return id;
  }
  
  stats() {
    return {
      trackedPrefixes: this.prefixCounts.size,
      compressedTokens: this.dictionary.size,
      dictionary: Object.fromEntries(this.dictionary)
    };
  }
}

module.exports = {
  fractalRoot,
  deriveFractalChild,
  hardwareId,
  verifyLocalHardware,
  createZkpIdentity,
  generateZkpId,
  createLinkProof,
  verifyLinkProof,
  AdaptiveGenerator
};
