// Type definitions for uniqid-pro
// Generated by uniqid-pro docgen

export interface EntropyInfo {
  bits: number;
  score: 'critical' | 'weak' | 'fair' | 'strong' | 'excellent' | 'cryptographic';
  icon: string;
  length: number;
  alphabetSize: number;
  collisionAt1K: string;
  collisionAt1M: string;
  collisionAt1B: string;
  safeFor: string[];
  unsafeFor: string[];
  recommendation: string;
}

export interface RandomnessInfo {
  verdict: 'appears-random' | 'suspicious' | 'biased' | 'too-short-to-test';
  chiSquared: { chiSq: number; pValue: string; verdict: string };
  runLength:  { longestRun: number; avgRun: number; verdict: string };
}

export interface DecodedId {
  type: string;
  raw: string;
  [key: string]: any;
}

export interface ParsedId {
  type: string;
  confidence: 'high' | 'medium' | 'low';
  decoded: DecodedId;
  allMatches: string[];
  suggestions: string[];
}

export interface LifecycleTransition {
  id: string;
  previous: string;
  state: string;
  timestamp: number;
}

export interface LifecycleHistory {
  from: string | null;
  to: string;
  id: string;
  timestamp: number;
  reason: string;
}

export interface LifecycleTimeline {
  state: string;
  enteredAt: string;
  reason: string | null;
  durationMs: number;
  duration: string;
  isCurrent: boolean;
}

export interface CollisionResult {
  ok: boolean;
  id: string;
  collision: boolean;
}

export interface CollisionStats {
  namespace: string;
  registrations: number;
  checks: number;
  collisions: number;
  collisionRate: string;
  bloomFillRatio: string;
  backendCount: number;
  backend: { ok: boolean; latencyMs: number; backend: string };
}

export interface FederationNodeStats {
  nodeId: string;
  machineId: number;
  strategy: string;
  generated: number;
  joinedAt: string;
  range: { start: number; end: number } | null;
}

export interface ComplianceReport {
  reportId: string;
  generatedAt: string;
  generatedBy: string;
  environment: string;
  frameworks: string[];
  verdict: 'COMPLIANT' | 'NON-COMPLIANT';
  overallCompliant: boolean;
  piiScan: { total: number; clean: number; flagged: number; byRisk: object };
  pseudonymization: { checked: number; compliant: number; violations: any[] };
  dataResidency: { checked: number; compliant: number; unknown: number; violations: any[] } | null;
  recommendations: string[];
  legalReferences: string[];
}

export interface DashboardSnapshot {
  capturedAt: string;
  uptimeMs: number;
  uptimeHuman: string;
  generation: { ratePerSec: number; byType: Record<string, number>; totalLifetime: number; series: any[] };
  latency: { p50: number; p75: number; p95: number; p99: number; min: number; max: number; mean: number } | null;
  collisions: { total: number; registrations: number; ratePercent: number; byNamespace: any[] };
  federation: { totalNodes: number; federations: any[] };
  alerts: { active: any[]; recent: any[]; newThisSnapshot: any[] };
}

export interface BatchVerifyResult {
  total: number;
  passed: number;
  failed: number;
  results: Array<{ id: string; pass: boolean; checks: Array<{ rule: string; pass: boolean }> }>;
}

export interface IdIndexEntry {
  id: string;
  type: string;
  tags: string[];
  meta: Record<string, any>;
  addedAt: number;
  decoded: DecodedId;
}

export interface QueryResult {
  total: number;
  results: IdIndexEntry[];
  offset: number;
  limit: number;
}

export interface UniqidError extends Error {
  name: 'UniqidError';
  code: string;
  meta: Record<string, any>;
  ts: string;
}

// ── UUID ──────────────────────────────────────────────────────────────────────
export function uuid(): string;
export function uuidV4(): string;
export function uuidV7(): string;
export function uuidV5(name: string, namespace?: string): string;
export function uuidV3(name: string): string;

// ── Sortable IDs ──────────────────────────────────────────────────────────────
export function ulid(): string;
export function ulidToTimestamp(ulid: string): number;
export function ksuid(): string;
export function ksuidToDate(ksuid: string): Date;
export function snowflakeId(): string;
export function parseSnowflake(id: string): { timestamp: number; date: Date };
export function timestampId(): string;

// ── Generators ────────────────────────────────────────────────────────────────
export function nanoId(size?: number, alphabet?: string): string;
export function humanId(): string;
export function typedId(type: string, size?: number): string;
export function fromPattern(pattern: string): string;
export function sequentialId(): string;
export function resetSequence(n?: number): void;
export function getSequence(): number;
export function otpToken(): string;

// ── Encoding ──────────────────────────────────────────────────────────────────
export function maskId(id: string, reveal?: number): string;
export function geoId(lat: number, lng: number): string;
export function parseGeoId(id: string): { lat: number; lng: number; rand: string } | null;
export function convertEncoding(id: string, from: string, to: string): string;

// ── Security ──────────────────────────────────────────────────────────────────
export function signId(id: string, key: string): string;
export function verifySignedId(signed: string, key: string): { valid: boolean; id: string };
export function encryptId(n: number, key: string): string;
export function decryptId(hex: string, key: string): number;
export function expiringId(opts?: { ttl?: '1h' | '1d' | '7d' }): string;
export function checkExpiry(id: string): { valid: boolean; expiresAt: Date; expired: boolean };

// ── Validation ────────────────────────────────────────────────────────────────
export function validate(id: string): { valid: boolean };
export function parse(id: string): { id: string; type: string };

// ── Performance ───────────────────────────────────────────────────────────────
export function batch<T>(fn: (...args: any[]) => T, n: number, ...args: any[]): T[];
export function batchUnique<T>(fn: (...args: any[]) => T, n: number): T[];
export function createPool(fn: () => string, size?: number): { get(): string };

// ── v3: Semantic IDs ──────────────────────────────────────────────────────────
export function semanticId(context: { type?: string; role?: string; region?: string; env?: string; [k: string]: any }, opts?: { secret?: string; separator?: string }): string;
export function validateSemantic(id: string, expected?: object, opts?: object): { valid: boolean; mismatch?: string[]; context: object };
export function parseSemantic(id: string, opts?: object): { type: string; tokens: string[]; random: string; raw: string };
export function registerSchema(type: string, schema: object): void;

// ── v3: Relationship IDs ──────────────────────────────────────────────────────
export function linkedId(parentId: string, opts?: { type?: string; secret?: string }): string;
export function verifyLink(childId: string, parentId: string, opts?: { secret?: string }): boolean;
export function deriveId(parentId: string, opts?: { reason?: string; secret?: string }): string;
export function isDescendantOf(childId: string, ancestorId: string, opts?: object): boolean;
export function getLineage(id: string): any[];
export function getChildren(parentId: string): string[];
export function clearLineage(): void;

// ── v3: Role-Scoped IDs ───────────────────────────────────────────────────────
export function scopedId(resourceId: string, opts?: { role?: string; secret?: string }): string;
export function resolveScoped(scoped: string, candidates: string[], opts?: object): string | null;
export function buildScopeMap(resourceIds: string[], opts?: object): Map<string, string>;

// ── v3: Lifecycle IDs ─────────────────────────────────────────────────────────
export function lifecycleId(entityType: string, opts?: { states?: string[]; initial?: string; secret?: string }): string;
export function transition(currentId: string, newState: string, opts?: { secret?: string; allowedTransitions?: Record<string, string[]>; reason?: string }): LifecycleTransition;
export function parseLifecycle(id: string, opts?: object): { valid: boolean; entityType?: string; state?: string; coreId?: string };
export function verifyState(id: string, expectedState: string, opts?: object): { valid: boolean; state: string; reason?: string };
export function stableCore(id: string): string;
export function getHistory(id: string): LifecycleHistory[];
export function getTimeline(id: string): LifecycleTimeline[];
export function replayHistory(id: string, opts?: object): { valid: boolean; states: string[]; violations: string[]; steps: number };
export function clearHistory(): void;

// ── v3: Entropy ───────────────────────────────────────────────────────────────
export function measuredId(opts?: { size?: number; alphabet?: string }): { id: string; entropy: EntropyInfo };
export function analyzeEntropy(id: string): EntropyInfo & { randomness?: RandomnessInfo };
export function sizeFor(opts?: { level?: string; population?: number; alphabet?: string }): { minChars: number; bits: number };
export function entropyBits(length: number, alphabetSize: number): number;
export function chiSquaredTest(id: string): { chiSq: number; pValue: string; verdict: string };
export function runLengthTest(id: string): { longestRun: number; avgRun: number; verdict: string };

// ── v3: DCID ──────────────────────────────────────────────────────────────────
export function dcid(inputs: string[], opts?: { key?: string; size?: number; version?: number }): string;
export function verifyDcid(id: string, inputs: string[], opts?: object): boolean;
export function idempotentId(inputs: string[], opts?: { key?: string; windowSeconds?: number; size?: number }): string;

// ── v3: Topology IDs ─────────────────────────────────────────────────────────
export function topoId(opts?: { region?: string; dc?: number; prefix?: string }): string;
export function parseTopology(id: string): { country: string; datacenter: number; region: string | null; timestamp: number; date: string; isEU: boolean; prefix: string | null };
export function isEUResident(id: string): boolean;
export function regionOf(id: string): string | null;
export function isSameRegion(idA: string, idB: string): boolean;
export function registerTopology(config: { region: string; dc?: number }): void;
export function registerRegion(regionKey: string, info: { country: string; zone: string; gdpr: boolean }): void;

// ── v4: Fuzzy IDs ─────────────────────────────────────────────────────────────
export function fuzzyId(opts?: { size?: number; prefix?: string; separator?: string }): string;
export function validateFuzzy(id: string): { valid: boolean; corrected?: string; autoFixed?: any[] };
export function correctFuzzy(id: string): { corrected: string | null; position?: number };
export function parseFuzzy(id: string, opts?: object): { prefix: string | null; body: string; checkChar: string; valid: boolean };

// ── v4: Compound IDs ─────────────────────────────────────────────────────────
export function compoundId(ids: string[], opts?: { sorted?: boolean; prefix?: string; tag?: string }): string;
export function splitId(id: string, opts?: { prefix?: string }): { ids: string[]; tag?: string; valid: boolean };
export function hasComponent(compound: string, componentId: string): boolean;
export function sharedComponents(a: string, b: string): string[];
export function timedCompoundId(ids: string[], opts?: object): string;
export function extractTimestamp(id: string): Date | null;

// ── v4: Hierarchy IDs ─────────────────────────────────────────────────────────
export function hierarchyRoot(opts?: { label?: string; size?: number }): string;
export function hierarchyChild(parentPath: string, opts?: { label?: string; size?: number }): string;
export function parseHierarchy(pathId: string): { segments: string[]; depth: number; root: string; parent: string | null; leaf: string; labels: string[] };
export function parentOf(pathId: string): string | null;
export function depthOf(pathId: string): number;
export function isDescendant(pathId: string, ancestorPath: string): boolean;
export function isDirectChild(pathId: string, parentPath: string): boolean;
export function subtreeRange(pathId: string): { gte: string; lt: string; prefix: string };
export function lowestCommonAncestor(pathA: string, pathB: string): string | null;
export function reparent(pathId: string, newParentPath: string): string;
export function topoSort(paths: string[]): string[];

// ── v4: Rate Limiter ──────────────────────────────────────────────────────────
export function createRateLimiter(opts?: { rate?: number; burst?: number; keyTTL?: number }): IdRateLimiter;
export class IdRateLimiter {
  consume(key: string, opts?: { cost?: number }): { allowed: boolean; remaining: number; retryAfterMs: number };
  wrap(fn: Function, key: string): Function;
  peek(key: string): { tokens: number; hits: number; blocked: number } | null;
  reset(key: string): void;
  report(): any[];
  destroy(): void;
}

// ── v4: Migration ─────────────────────────────────────────────────────────────
export function migrateId(oldId: string, opts?: { toVersion?: string; reason?: string; secret?: string }): { newId: string; oldId: string; oldFormat: string; version: string };
export function recoverOriginal(migratedId: string, opts?: { secret?: string }): { originalId: string | null; version: string | null; valid: boolean; integrityOk?: boolean };
export function batchMigrate(ids: string[], opts?: object): any[];
export function isMigrated(id: string): boolean;
export function detectFormat(id: string): { format: string; meta: object };
export function getMigrationLog(opts?: { limit?: number }): any[];

// ── v5: Collision Detection ───────────────────────────────────────────────────
export function createDetector(opts?: { namespace?: string; backend?: any; bloomCapacity?: number; onCollision?: Function }): CollisionDetector;
export function createRegistry(opts?: object): { namespace(name: string): CollisionDetector; globalStats(): Promise<object>; namespaces(): string[] };
export class CollisionDetector {
  namespace: string;
  isUnique(id: string): Promise<{ unique: boolean; checkedAt: number; layers: object }>;
  register(id: string, opts?: { meta?: object; throwOnCollision?: boolean }): Promise<CollisionResult>;
  checkAndRegister(id: string, opts?: object): Promise<CollisionResult>;
  registerBatch(ids: string[], opts?: object): Promise<{ registered: string[]; collisions: string[] }>;
  stats(): Promise<CollisionStats>;
  clear(): Promise<void>;
}

// ── v5: Federation ────────────────────────────────────────────────────────────
export function createFederation(opts?: { name?: string; strategy?: 'snowflake' | 'prefix' | 'range' | 'epoch'; rangeSize?: number; maxNodes?: number }): Federation;
export class Federation {
  name: string;
  strategy: string;
  join(nodeId: string): FederationNode;
  verify(id: string): { owner: string | null; strategy: string; parsed: object };
  stats(): { name: string; strategy: string; nodes: number; totalGenerated: number; nodeStats: FederationNodeStats[] };
}
export class FederationNode {
  nodeId: string;
  machineId: number;
  generate(opts?: object): string;
  generateBatch(count: number): string[];
  stats(): FederationNodeStats;
  leave(): void;
}

// ── v5: Compliance ────────────────────────────────────────────────────────────
export function scanForPII(id: string): { clean: boolean; findings: any[]; riskLevel: string };
export function scanBatch(ids: string[]): { summary: object; results: any[] };
export function verifyPseudonymization(id: string, opts?: object): { compliant: boolean; checks: any[]; verdict: string };
export function checkDataResidency(id: string, opts?: { requiredFramework?: string; allowedRegions?: string[] }): { compliant: boolean | null; region: string | null; framework: string; detail: string };
export function generateComplianceReport(ids: string[], opts?: { framework?: string; checkResidency?: boolean; environment?: string }): ComplianceReport;
export function formatReport(report: ComplianceReport): string;

// ── v5: Dashboard ─────────────────────────────────────────────────────────────
export function createDashboard(opts?: { telemetry?: any; detectors?: any; federations?: any; maxHistory?: number }): Dashboard;
export class Dashboard {
  snapshot(): Promise<DashboardSnapshot>;
  watch(intervalMs: number, cb: (snap: DashboardSnapshot) => void): this;
  stopWatching(): this;
  ascii(snap?: DashboardSnapshot): Promise<string>;
  addAlert(rule: { name: string; severity?: string; condition: (m: any) => boolean; message: string | Function }): this;
}

// ── v6: Decode & Parse ────────────────────────────────────────────────────────
export function decodeId(id: string): DecodedId;
export function parseId(id: string): ParsedId;
export function decodeBatch(ids: string[]): DecodedId[];
export function registerDecoder(type: string, decoder: { detect: (id: string) => boolean; decode: (id: string) => object }): void;

// ── v6: Storage ───────────────────────────────────────────────────────────────
export function createStore(opts?: { backend?: 'memory' | 'file' | object; filePath?: string }): PersistentStore;
export class PersistentStore {
  addLineageEntry(parentId: string, entry: object): Promise<void>;
  getLineage(id: string): Promise<any[]>;
  getChildren(parentId: string): Promise<string[]>;
  clearLineage(): Promise<void>;
  get(key: string): Promise<any>;
  set(key: string, value: any): Promise<void>;
  backendName: string;
}

// ── v6: Batch & Comparison ───────────────────────────────────────────────────
export function batchVerify(ids: string[], rules: Array<{ name: string; fn: (id: string) => boolean }>): BatchVerifyResult;
export function batchVerifySigned(items: Array<{ id: string; signature: string }>, key: string): Array<{ id: string; valid: boolean }>;
export function batchCheckCollisions(ids: string[]): { total: number; unique: number; duplicates: any[]; hasDuplicates: boolean };
export function batchValidate(ids: string[], pattern: RegExp | Function): { total: number; valid: number; invalid: number; results: any[] };
export function compareIds(a: string, b: string): { equal: boolean; sameType: boolean; order: -1 | 0 | 1; typeA: string; typeB: string };
export function sortById(ids: string[], direction?: 'asc' | 'desc'): string[];
export function diffIds(a: string[], b: string[]): { onlyInA: string[]; onlyInB: string[]; inBoth: string[] };
export function groupByType(ids: string[]): Record<string, string[]>;
export function deduplicateIds(ids: string[]): string[];

// ── v6: Query System ─────────────────────────────────────────────────────────
export function createIndex(): IdIndex;
export class IdIndex {
  add(id: string, opts?: { tags?: string[]; meta?: object }): this;
  tag(id: string, ...tags: string[]): this;
  untag(id: string, ...tags: string[]): this;
  remove(id: string): boolean;
  query(filter?: { type?: string; tags?: string[]; tagMode?: 'all' | 'any'; meta?: object; since?: number; until?: number; search?: string; limit?: number; offset?: number; orderBy?: string; order?: 'asc' | 'desc' }): QueryResult;
  get(id: string): IdIndexEntry | null;
  getByTag(tag: string): string[];
  getByType(type: string): string[];
  allTags(): string[];
  allTypes(): string[];
  stats(): { total: number; byType: object; byTag: object; tags: number };
  export(): IdIndexEntry[];
  import(entries: IdIndexEntry[]): this;
}

// ── v6: Collision Prevention + Versioning ────────────────────────────────────
export function createSafeGenerator(fn: Function, opts?: { namespace?: string; maxRetries?: number; onExhaust?: Function }): { generate(...args: any[]): string; generateBatch(n: number): string[]; stats(): object; reset(): void };
export function registerVersion(name: string, version: number, schema: { generate: (data?: object) => string; validate?: (id: string) => boolean }): void;
export function versionedGenerate(name: string, data?: object): { id: string; version: number; name: string };
export function detectVersion(name: string, id: string): number | null;
export function registerMigration(name: string, fromVersion: number, toVersion: number, fn: (id: string) => string): void;
export function migrateVersion(name: string, id: string, opts: { fromVersion: number; toVersion: number }): { id: string; originalId: string; steps: any[]; fromVersion: number; toVersion: number };

// ── v6: Plugin / Events / Config ─────────────────────────────────────────────
export function configure(opts: { logLevel?: string; defaultSize?: number; defaultSecret?: string; traceMode?: boolean; cacheEnabled?: boolean; [k: string]: any }): void;
export function getConfig(key?: string): any;
export function on(event: string, handler: (payload: { event: string; data: any; timestamp: number }) => void): () => void;
export function off(event: string, handler: Function): void;
export function once(event: string, handler: Function): () => void;
export function emit(event: string, data?: object): void;
export function registerWebhook(opts: { url: string; events?: string[]; secret?: string }): void;
export function use(middleware: { name: string; before?: (ctx: object) => object; after?: (ctx: object) => object }): void;
export function applyMiddleware(generatorName: string, generatorFn: Function): Function;
export function listPlugins(): Array<{ name: string; hooks: string[] }>;

// ── v6: Async / Cache / Access Control ───────────────────────────────────────
export function streamIds(generatorFn: Function, opts?: { count?: number; chunkSize?: number; delayMs?: number }): AsyncGenerator<string>;
export function collectFromStream(stream: AsyncIterable<string>, n: number): Promise<string[]>;
export function generateAsync(generatorFn: Function, total: number, opts?: { onProgress?: Function; chunkSize?: number }): Promise<string[]>;
export function createCache(opts?: { maxSize?: number; ttlMs?: number }): { get(key: string): any; set(key: string, value: any): void; has(key: string): boolean; stats(): object };
export function withCache(fn: Function, opts?: object): Function;
export function createAccessControl(): { defineRole(role: string, permissions: string[]): any; addPolicy(policy: object): any; check(role: string, action: string, id: string): { allowed: boolean; reason?: string }; listRoles(): object };

// ── v6: DevTools ──────────────────────────────────────────────────────────────
export const ErrorCodes: { COLLISION: string; RATE_LIMITED: string; INVALID_ID: string; EXPIRED: string; PERMISSION: string; VALIDATION: string; NOT_FOUND: string; EXHAUSTED: string; SCHEMA_MISMATCH: string };
export function createError(code: string, message: string, meta?: object): UniqidError;
export const logger: { error(...a: any[]): void; warn(...a: any[]): void; info(...a: any[]): void; debug(...a: any[]): void; setLevel(l: string): void; history(n?: number): any[] };
export function enableTrace(): void;
export function disableTrace(): void;
export function trace<T>(label: string, fn: () => T): T;
export function getTraces(n?: number): any[];
export function createValidationEngine(): { addRule(name: string, fn: (id: string) => true | string, meta?: object): any; validate(id: string, rules?: string[]): { valid: boolean; violations: any[] }; validateBatch(ids: string[]): object; listRules(): any[] };
export function createCommonRules(): ReturnType<typeof createValidationEngine>;
export function exportIds(ids: string[], opts?: { meta?: object; format?: 'json' | 'csv' | 'object' }): string | object;
export function importIds(data: string | object): { ids: string[]; meta: object; count: number };
export function enableMockMode(): void;
export function disableMockMode(): void;
export function mockGenerator(generatorName: string, mockValue: string | Function): void;
export function withMock(name: string, generatorFn: Function): Function;
export function testIds(prefix?: string, count?: number): string[];
export function assertId(id: string, expectations?: { type?: string; length?: number; minLength?: number; pattern?: RegExp; prefix?: string }): { pass: boolean; failures: string[] };

// ── v6: Retry / Monitor / CLI / Docs ─────────────────────────────────────────
export function withRetry<T>(fn: (...args: any[]) => Promise<T>, opts?: { retries?: number; backoffMs?: number; fallback?: Function; onRetry?: Function }): (...args: any[]) => Promise<T>;
export function withFallback(...fns: Function[]): (...args: any[]) => Promise<any>;
export const monitor: { count(name: string, value?: number): void; gauge(name: string, value: number): void; timing(name: string, ms: number): void; probe(name: string, fn: () => object): any; snapshot(): object; history(n?: number): any[]; reset(): void };
export function parseCLIArgs(argv: string[]): { command: string; args: string[]; flags: Record<string, any> };
export function executeCLI(parsed: ReturnType<typeof parseCLIArgs>, uid: object): string;
export function generateSchemaDocs(schemaDef: { name: string; description?: string; segments?: any[]; examples?: string[] }): string;
export function generateTypeScript(schemaDef: { name: string; segments?: any[] }): string;
export function generateDocs(schemas: any[], opts?: { format?: 'markdown' | 'typescript'; title?: string }): string;
